// Standard disclaimers, signature block, Document Integrity section, and the
// optional Formal Attestation block. Extracted verbatim from the pre-split
// builder — zero behavior change.
import { sanitizePdfText } from "@/lib/pdfText";
import { type SignatureFormat } from "@/lib/signatureVerify";
import { buildControlDisclaimerLine, buildFormatPhrase } from "./pof-pdf-strings";
import { formatUnix } from "./address-helpers";
import { KYUTXO_APP_VERSION } from "./declaration-prefs";
import type { PdfLayout, PofPdfData } from "./pof-pdf-context";

export function renderDisclaimersAndSignature(L: PdfLayout, d: PofPdfData) {
  const { doc, margin } = L;
  const { addLine, addWrapped, addSpacer, checkPageBreak } = L;
  const {
    effRows,
    effVerifiedRows,
    hasVerified,
    allVerified,
    effDate,
    generationTimestamp,
  } = d;

  // ── Standard Disclaimers ───────────────────────────────────────────────
  checkPageBreak(50);
  addLine("DISCLAIMERS", 11, true);
  addSpacer(2);

  const verifiedFormats = new Set(
    effVerifiedRows
      .map((r) => r.verifiedFormat)
      .filter((f): f is SignatureFormat => !!f)
  );
  const formatPhrase = buildFormatPhrase(verifiedFormats);

  const controlDisclaimerLine = buildControlDisclaimerLine({
    allVerified,
    hasVerified,
    verifiedCount: effVerifiedRows.length,
    totalCount: effRows.length,
    formatPhrase,
  });

  const disclaimers = [
    "1. This is a declaration produced by the declarant personally attesting to ownership of the above Bitcoin addresses.",
    controlDisclaimerLine,
    "3. Balances reflect the data source indicated above and may not represent real-time on-chain state.",
    "4. This document was generated offline using KYUTXO. No data was transmitted to third parties during generation.",
    "5. This document does not constitute financial, legal, or tax advice.",
  ];
  for (const dLine of disclaimers) {
    addWrapped(dLine);
    addSpacer(1);
  }

  addSpacer(6);

  // ── Signature Block ────────────────────────────────────────────────────
  checkPageBreak(30);
  addLine("SIGNATURE", 11, true);
  addSpacer(4);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text("Declarant signature: ___________________________________", margin, L.y);
  L.y += 8;
  doc.text(`Date: ${sanitizePdfText(effDate)}`, margin, L.y);
  L.y += 6;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    sanitizePdfText(
      `Generated by KYUTXO on ${generationTimestamp.toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
      })}`
    ),
    margin,
    L.y
  );
  doc.setTextColor(0, 0, 0);
  L.y += 5;
}

export function renderDocumentIntegrity(L: PdfLayout, d: PofPdfData) {
  const { doc, margin, contentW } = L;
  const { checkPageBreak } = L;
  const {
    isSample,
    effNonce,
    effSummary,
    generationIso,
    contentFingerprint,
    canonicalPayload,
  } = d;

  // ── Document Integrity (always-on) ────────────────────────────────────
  checkPageBreak(55);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("DOCUMENT INTEGRITY", margin, L.y);
  L.y += 5;
  doc.setLineWidth(0.3);
  doc.line(margin, L.y, margin + contentW, L.y);
  L.y += 4;

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);

  // Generation metadata
  // NOTE: Generated timestamp is displayed as UTC ISO 8601 — this is exactly the
  // value in the canonical payload so the fingerprint is unambiguously reproducible.
  const metaLines: [string, string][] = [
    ["Tool:", `KYUTXO v${KYUTXO_APP_VERSION} (Proof of Funds Declaration)`],
    ["Generated (UTC ISO 8601):", generationIso],
    ["Declaration Reference:", effNonce],
  ];

  // Blockchain time-anchor
  if (effSummary?.blockHeight) {
    const anchorLabel = effSummary.timestamp
      ? `Block ${effSummary.blockHeight.toLocaleString()} — ${formatUnix(effSummary.timestamp)}`
      : `Block ${effSummary.blockHeight.toLocaleString()}`;
    metaLines.push(["On-chain data current as of:", anchorLabel]);
  } else if (effSummary?.timestamp) {
    metaLines.push(["On-chain data as of:", formatUnix(effSummary.timestamp)]);
  }

  // Content fingerprint (red in sample mode to make the specimen label visually obvious)
  if (isSample) {
    metaLines.push(["Content Fingerprint (SHA-256):", ""]);
  } else {
    metaLines.push(["Content Fingerprint (SHA-256):", contentFingerprint]);
  }

  const metaLabelW = 65;
  const metaValueW = contentW - metaLabelW;
  for (const [label, value] of metaLines) {
    checkPageBreak(10);
    doc.setFont("helvetica", "bold");
    doc.text(sanitizePdfText(label), margin, L.y);
    doc.setFont("helvetica", "normal");
    if (label.startsWith("Content Fingerprint") && isSample) {
      doc.setTextColor(180, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text(sanitizePdfText(contentFingerprint), margin + metaLabelW, L.y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);
      L.y += 4.5;
    } else {
      const valLines = doc.splitTextToSize(sanitizePdfText(value), metaValueW) as string[];
      doc.text(valLines, margin + metaLabelW, L.y);
      L.y += Math.max(valLines.length * 8.5 * 0.45, 4.5);
    }
  }
  L.y += 2;

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);

  if (isSample) {
    // In sample mode, skip the canonical payload box and explain why
    const sampleFpNote =
      "SPECIMEN — No canonical payload is printed for sample PDFs. " +
      "The Content Fingerprint above is a placeholder label, not a valid SHA-256 hash. " +
      "A real declaration includes the verbatim preimage here so any reviewer can independently verify the fingerprint.";
    const sampleFpLines = doc.splitTextToSize(sanitizePdfText(sampleFpNote), contentW) as string[];
    doc.text(sampleFpLines, margin, L.y);
    doc.setTextColor(0, 0, 0);
    L.y += sampleFpLines.length * 7.5 * 0.45 + 4;
  } else {
    const fingerprintNote =
      "The Content Fingerprint is SHA-256(UTF-8(canonical payload)), where the canonical payload " +
      "is the verbatim preimage printed below (lines joined by newline \"\\n\"). " +
      "It covers: tool version, reference ID, all declarant fields, date, purpose, statement, " +
      "all declared addresses with balances and control status, proof-of-control challenge messages " +
      "and signatures for verified addresses, blockchain anchor, fiat rate, all section toggle states " +
      "and their user-entered fields, and the UTC ISO 8601 generation timestamp. " +
      "A reviewer can copy the preimage below, UTF-8 encode it, SHA-256 hash it, and verify the hex matches the fingerprint above. " +
      "Page numbering in the footer confirms no pages have been removed.";
    const fpNoteLines = doc.splitTextToSize(sanitizePdfText(fingerprintNote), contentW) as string[];
    doc.text(fpNoteLines, margin, L.y);
    doc.setTextColor(0, 0, 0);
    L.y += fpNoteLines.length * 7.5 * 0.45 + 4;

    // ── Canonical payload (verbatim preimage) ───────────────────────────
    // Printed in full so any third party can recompute the fingerprint independently
    // without possessing any information not visible in this document.
    checkPageBreak(20);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Fingerprint Preimage (canonical payload, reproduced verbatim):", margin, L.y);
    L.y += 4.5;

    // Print payload in Courier at small size, with a light background box
    doc.setFont("courier", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(30, 30, 30);
    const payloadWrapped = doc.splitTextToSize(
      sanitizePdfText(canonicalPayload),
      contentW - 4
    ) as string[];
    const payloadBoxH = payloadWrapped.length * 6.5 * 0.42 + 4;
    checkPageBreak(payloadBoxH + 4);
    doc.setFillColor(248, 248, 248);
    doc.setDrawColor(200, 200, 200);
    doc.rect(margin, L.y - 1.5, contentW, payloadBoxH, "FD");
    doc.text(payloadWrapped, margin + 2, L.y + 1);
    L.y += payloadBoxH + 4;
    doc.setTextColor(0, 0, 0);
  }
}

export function renderFormalAttestation(L: PdfLayout, d: PofPdfData) {
  const { doc, margin, contentW } = L;
  const { checkPageBreak } = L;
  const { effName, effDate, effNonce } = d;
  const { includeAttestation, attestationPlaceOfSigning, attestationWitnessLine } = d.params;

  // ── Optional Attestation Block ─────────────────────────────────────────
  if (!includeAttestation) return;

  checkPageBreak(70);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("FORMAL ATTESTATION", margin, L.y);
  L.y += 5;
  doc.setLineWidth(0.5);
  doc.line(margin, L.y, margin + contentW, L.y);
  L.y += 5;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  const attestText =
    `I, ${sanitizePdfText(effName)}, hereby solemnly declare and attest that the foregoing ` +
    "information — including all Bitcoin addresses, reported balances, and supporting details — is true, " +
    "accurate, and complete to the best of my knowledge and belief. I am the lawful owner or authorised " +
    "signatory of the declared addresses and the funds associated with them. I understand that knowingly " +
    "making a false declaration may result in civil and/or criminal liability under applicable law.";
  const attestLines = doc.splitTextToSize(sanitizePdfText(attestText), contentW) as string[];
  doc.text(attestLines, margin, L.y);
  L.y += attestLines.length * 9 * 0.45 + 8;

  // Signature line
  checkPageBreak(50);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Declarant signature: _______________________________________________", margin, L.y);
  L.y += 8;
  doc.text(`Full name: ${sanitizePdfText(effName)}`, margin, L.y);
  L.y += 7;

  const placeSigned = attestationPlaceOfSigning.trim();
  if (placeSigned) {
    doc.text(`Place of signing: ${sanitizePdfText(placeSigned)}`, margin, L.y);
    L.y += 7;
  } else {
    doc.text("Place of signing: _______________________________________________", margin, L.y);
    L.y += 7;
  }

  doc.text(`Date: ${sanitizePdfText(effDate)}`, margin, L.y);
  L.y += 10;

  // Optional witness / notary line
  const witnessLine = attestationWitnessLine.trim();
  if (witnessLine) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    const wLines = doc.splitTextToSize(sanitizePdfText(`Witness / Notary: ${witnessLine}`), contentW) as string[];
    doc.text(wLines, margin, L.y);
    doc.setFont("helvetica", "normal");
    L.y += wLines.length * 9 * 0.45 + 5;
  } else {
    doc.text("Witness / Notary signature: ____________________________________", margin, L.y);
    L.y += 7;
    doc.text("Witness / Notary name and capacity: ____________________________", margin, L.y);
    L.y += 7;
    doc.text("Date: _______________", margin, L.y);
    L.y += 7;
  }

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text(
    sanitizePdfText(`Declaration Reference: ${effNonce}`),
    margin, L.y
  );
  doc.setTextColor(0, 0, 0);
  L.y += 8;
}
