// Guards the Proof of Funds content fingerprint against silent drift.
//
// The SHA-256 fingerprint printed in the PDF's Document Integrity section is
// computed from the canonical payload built in pof-pdf-data.ts. After the
// section-module refactor, a change to any module could accidentally change
// (or stop covering) what the fingerprint hashes. This suite feeds fixed
// params into computePofPdfData and asserts:
//   1. the EXACT canonical payload lines, and
//   2. that the reported fingerprint hex equals an independently computed
//      SHA-256 of that exact payload.
// Any change to the canonical line structure must be made deliberately here.
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createHash } from "node:crypto";
import { computePofPdfData } from "./pof-pdf-data";
import { KYUTXO_APP_VERSION } from "./declaration-prefs";
import type { UsePofPdfBuilderParams } from "./pof-pdf-context";

const FIXED_NOW = "2026-07-28T12:00:00.000Z";

const ADDR_VERIFIED = "bc1qtestaddr000000000000000000000000000001";
const ADDR_UNVERIFIED = "1TestAddrTwo1111111111111111111111";

function fixedParams(): UsePofPdfBuilderParams {
  return {
    declarantName: "Alice Example",
    declarantContact: " alice@example.com ", // padded — canonical line must be trimmed
    declarantResidentialAddress: "1 Test Lane, Testville",
    declarantDob: "1990-05-06",
    declarantTaxId: "TAX-123",
    declarantIdNumber: "", // blank — must produce NO canonical line
    declarantNationality: "Exampleland",
    declarationDate: "2026-01-02",
    declarationNonce: "abc123def4567890",
    purpose: "Bank onboarding",
    statement: "  I declare these funds are mine.  ",
    summary: {
      totalSats: 150_000,
      source: "node" as any,
      asOfLabel: "Live node query",
      blockHeight: 850_000,
      timestamp: 1_735_689_600,
    },
    doneRows: [
      { raw: ADDR_VERIFIED, isInvalid: false, status: "done" as any, balanceSats: 150_000 },
      // balanceSats intentionally undefined — canonical line must render 0 sat
      { raw: ADDR_UNVERIFIED, isInvalid: false, status: "done" as any },
    ],
    totalSats: 150_000,
    fiatValid: true,
    fiatTotal: 75,
    fiatCurrency: "EUR",
    fiatRateNum: 50_000,
    controlStates: {
      [ADDR_VERIFIED]: {
        paste: "",
        status: "verified" as any,
        verifiedSig: "c2lnbmF0dXJlLXBsYWNlaG9sZGVy",
        verifiedFormat: "bip322" as any,
      },
      [ADDR_UNVERIFIED]: { paste: "", status: "idle" as any },
    },
    evidenceItems: [
      {
        id: "ev-1",
        name: "statement.png",
        kind: "image" as any,
        mime: "image/png",
        bytes: new Uint8Array([1, 2, 3]),
        caption: " Bank statement ", // padded — canonical line must be trimmed
        sha256: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
        size: 3,
      } as any,
    ],
    includeProvenance: false,
    provenanceFiatCurrency: "USD",
    includeQr: true,
    qrExplorerId: "mempool" as any,
    qrPreviews: {},
    includeAml: true,
    amlPepStatus: "no",
    amlTaxJurisdiction: "DE",
    amlSourceOfWealth: "Salary",
    amlSourceOfFunds: "", // blank — must produce NO canonical line
    amlTaxStatement: "",
    amlScreeningResult: null,
    includeIntro: false,
    includeAttestation: true,
    attestationPlaceOfSigning: "Berlin",
    attestationWitnessLine: "", // blank — must produce NO canonical line
    includeGlossary: true,
    verifierReference: "",
    freshnessAnchorEnabled: false,
    freshnessAnchor: null,
  };
}

// The challenge message exactly as buildChallengeMessage derives it from the
// declaration fields above (reproduced literally so drift in either the
// canonical payload OR the challenge derivation is caught).
const EXPECTED_CHALLENGE = [
  "I certify that I control the following Bitcoin address.",
  "",
  "Declarant: Alice Example",
  "Purpose:   Bank onboarding",
  "Date:      2026-01-02",
  "Reference: abc123def4567890",
  `Address:   ${ADDR_VERIFIED}`,
  "",
  "Generated by KYUTXO for a Proof of Funds Declaration.",
].join("\n");

const EXPECTED_LINES = [
  "KYUTXO-POF-v1",
  `TOOL: KYUTXO v${KYUTXO_APP_VERSION}`,
  "REF: abc123def4567890",
  "DECLARANT: Alice Example",
  "CONTACT: alice@example.com",
  "RESIDENTIAL: 1 Test Lane, Testville",
  "DOB: 1990-05-06",
  "TAX_ID: TAX-123",
  "NATIONALITY: Exampleland",
  "DATE: 2026-01-02",
  "PURPOSE: Bank onboarding",
  "STATEMENT: I declare these funds are mine.",
  "ADDRESSES:",
  `${ADDR_VERIFIED}: 150000 sat [VERIFIED]`,
  `${ADDR_UNVERIFIED}: 0 sat [UNVERIFIED]`,
  "TOTAL: 150000 sat",
  "SOURCE: Live node query",
  "BLOCK: 850000",
  "TIMESTAMP: 1735689600",
  "FIAT_RATE: 50000 EUR",
  `CTRL_${ADDR_VERIFIED}_CHALLENGE: ${EXPECTED_CHALLENGE}`,
  `CTRL_${ADDR_VERIFIED}_SIG: c2lnbmF0dXJlLXBsYWNlaG9sZGVy`,
  "SECTION_QR: ON:mempool",
  "SECTION_PROVENANCE: OFF",
  "SECTION_AML: ON",
  "AML_PEP: no",
  "AML_WEALTH: Salary",
  "AML_TAX_JUR: DE",
  "SECTION_ATTESTATION: ON",
  "ATTEST_PLACE: Berlin",
  "SECTION_INTRO: OFF",
  "SECTION_GLOSSARY: ON",
  "EVIDENCE_COUNT: 1",
  "EVIDENCE_ITEM_001: image|statement.png|deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef|Bank statement",
  `GENERATED: ${FIXED_NOW}`,
];

describe("computePofPdfData canonical payload / fingerprint", () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date(FIXED_NOW));
  });
  afterEach(() => {
    vi.useRealTimers();
  });

  it("produces the exact canonical payload lines for fixed input", async () => {
    const data = await computePofPdfData(fixedParams(), false);
    // Compare joined strings so a failure shows a readable line-level diff.
    expect(data.canonicalPayload).toBe(EXPECTED_LINES.join("\n"));
  });

  it("fingerprint is the SHA-256 hex of the exact canonical payload", async () => {
    const data = await computePofPdfData(fixedParams(), false);
    const expectedHex = createHash("sha256")
      .update(Buffer.from(EXPECTED_LINES.join("\n"), "utf8"))
      .digest("hex");
    expect(data.contentFingerprint).toMatch(/^[0-9a-f]{64}$/);
    expect(data.contentFingerprint).toBe(expectedHex);
  });

  it("blank optional fields stay excluded (no empty canonical lines)", async () => {
    const data = await computePofPdfData(fixedParams(), false);
    // Note: the embedded challenge message legitimately contains blank lines,
    // so we assert the specific omitted keys rather than "no empty lines".
    expect(data.canonicalPayload).not.toContain("ID_NUMBER:");
    expect(data.canonicalPayload).not.toContain("AML_FUNDS:");
    expect(data.canonicalPayload).not.toContain("AML_TAX_STMT:");
    expect(data.canonicalPayload).not.toContain("ATTEST_WITNESS:");
  });

  it("sample mode never produces a real fingerprint or payload", async () => {
    const data = await computePofPdfData(fixedParams(), true);
    expect(data.contentFingerprint).toBe("SPECIMEN — NOT A VALID FINGERPRINT (sample PDF)");
    expect(data.canonicalPayload).toBe("");
  });
});
