// @vitest-environment jsdom
//
// Regression guard for the garbled-text vector in the Privacy Audit history PDF
// export (`buildPrivacyHistoryPdf` in privacy-history-export.ts).
//
// jsPDF's Standard-14 Helvetica has no embedded Unicode font, so any text run
// outside the WinAnsi (Windows-1252) range is emitted as a UTF-16BE byte stream
// that renders as garbled glyphs. The fix routes the record-derived free-text
// fields (the report-wide scope label and the per-run Owner/Wallet columns)
// through `sanitizePdfText`. If a future edit drops one of those wrappers, a
// non-Latin owner or wallet name would silently reintroduce a UTF-16BE run.
//
// `buildPrivacyHistoryPdf` returns a Blob directly (doc.output("blob")), so we
// just inspect the real generated bytes.

import { describe, it, expect } from "vitest";

import { extractPdfText, pdfHasUtf16beRuns } from "@/test/pdfAssertions";
import type { PrivacyAuditHistoryEntry } from "@/lib/database";
import { buildPrivacyHistoryPdf } from "./privacy-history-export";

// Non-WinAnsi owner/wallet names live above U+00FF, so before sanitization they
// would each force a UTF-16BE run — both directly in the per-run table columns
// and in the report-wide scope label (all runs share the same owner/wallet).
const NON_LATIN_OWNER = "持有人_愛麗絲";
const NON_LATIN_WALLET = "冷錢包_測試";

function entry(
  overrides: Partial<PrivacyAuditHistoryEntry> = {},
): PrivacyAuditHistoryEntry {
  return {
    id: 1,
    timestamp: Date.UTC(2025, 0, 1),
    score: 85,
    grade: "B",
    totalFindings: 3,
    transactionsAnalyzed: 10,
    addressesScanned: 5,
    severityCounts: { CRITICAL: 0, HIGH: 1, MEDIUM: 1, LOW: 1 },
    findingTypeCounts: { address_reuse: 2, common_input_ownership: 1 },
    owner: NON_LATIN_OWNER,
    walletName: NON_LATIN_WALLET,
    ...overrides,
  } as PrivacyAuditHistoryEntry;
}

describe("Privacy Audit history PDF — WinAnsi safety", () => {
  it("emits no UTF-16BE runs even with non-Latin owner/wallet names", async () => {
    // Two runs sharing the same scope so the scope-label surface is exercised
    // and the trend sparkline (needs >= 2 points) is drawn.
    const blob = await buildPrivacyHistoryPdf([
      entry({ id: 1, timestamp: Date.UTC(2025, 0, 1), score: 70 }),
      entry({ id: 2, timestamp: Date.UTC(2025, 1, 1), score: 85 }),
    ]);

    // The smoking gun: any UTF-16BE run means a record-derived string skipped
    // sanitizePdfText and will render as garbled glyphs.
    expect(await pdfHasUtf16beRuns(blob)).toBe(false);

    const text = await extractPdfText(blob);
    // ASCII scaffolding proves the document rendered and the non-Latin glyphs
    // were substituted with "?".
    expect(text).toContain("Privacy Score History");
    expect(text).toContain("Scope:");
    expect(text).toContain("?");
  });

  it("would catch a bypass: raw non-Latin text DOES produce UTF-16BE runs", async () => {
    // Control proving the guard above is meaningful: a regression dropping the
    // wrapper would emit exactly this, which must trip the detector.
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    doc.text(`Owner: ${NON_LATIN_OWNER}`, 14, 20);
    const rawBlob = doc.output("blob");
    expect(await pdfHasUtf16beRuns(rawBlob)).toBe(true);
  });
});
