// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fund-trail/FullScreenBreakout.tsx": () => import("../components/mockups/fund-trail/FullScreenBreakout.tsx"),
  "./components/mockups/fund-trail/HorizontalHopTimeline.tsx": () => import("../components/mockups/fund-trail/HorizontalHopTimeline.tsx"),
  "./components/mockups/fund-trail/SankeyFlow.tsx": () => import("../components/mockups/fund-trail/SankeyFlow.tsx"),
  "./components/mockups/fund-trail/VerticalTimelineScroll.tsx": () => import("../components/mockups/fund-trail/VerticalTimelineScroll.tsx")
};
