import { useState, useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { 
  Search,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDownUp,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowBigDown,
  ArrowBigUp,
  Activity,
  Anchor,
  Archive,
  AtSign,
  Award,
  Ban,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Bell,
  BellOff,
  BellRing,
  Bluetooth,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  CircleDot,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Code2,
  Cog,
  Coins,
  Columns,
  Command,
  Compass,
  Component,
  Contact,
  Copy,
  CopyCheck,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  Database,
  Delete,
  Diamond,
  Disc,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  Feather,
  File,
  FileCheck,
  FileCode,
  FileJson,
  FileMinus,
  FilePlus,
  FileSearch,
  FileText,
  FileWarning,
  FileX,
  Files,
  Filter,
  FilterX,
  Flag,
  Flame,
  FlipHorizontal,
  FlipVertical,
  Folder,
  FolderCheck,
  FolderClosed,
  FolderDown,
  FolderInput,
  FolderMinus,
  FolderOpen,
  FolderOutput,
  FolderPlus,
  FolderSearch,
  FolderUp,
  FolderX,
  Folders,
  FormInput,
  Forward,
  Frame,
  Frown,
  Gauge,
  Gift,
  GitBranch,
  GitCommit,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  Globe2,
  Grab,
  GraduationCap,
  Grid,
  Grid2X2,
  Grid3X3,
  Grip,
  GripHorizontal,
  GripVertical,
  Hammer,
  Hand,
  HandMetal,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartOff,
  HelpCircle,
  Hexagon,
  History,
  Home,
  Image,
  ImageMinus,
  ImageOff,
  ImagePlus,
  Import,
  Inbox,
  Indent,
  IndianRupee,
  Infinity,
  Info,
  Inspect,
  Instagram,
  Italic,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Laptop2,
  Lasso,
  LassoSelect,
  Laugh,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LightbulbOff,
  LineChart,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListChecks,
  ListEnd,
  ListFilter,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListStart,
  ListTodo,
  ListTree,
  ListVideo,
  ListX,
  Loader,
  Loader2,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailSearch,
  MailWarning,
  MailX,
  Mails,
  Map,
  MapPin,
  MapPinOff,
  Maximize,
  Maximize2,
  Megaphone,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  MonitorOff,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MousePointer,
  MousePointer2,
  MousePointerClick,
  Move,
  Move3d,
  MoveDown,
  MoveDownLeft,
  MoveDownRight,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveUpLeft,
  MoveUpRight,
  MoveVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Network,
  Newspaper,
  Octagon,
  Option,
  Outdent,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Paintbrush,
  Paintbrush2,
  Palette,
  Palmtree,
  Paperclip,
  Pause,
  PauseCircle,
  PauseOctagon,
  PenTool,
  Pencil,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  PiggyBank,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  Play,
  PlayCircle,
  Plug,
  Plug2,
  PlugZap,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Podcast,
  Pointer,
  Power,
  PowerOff,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Radio,
  RadioReceiver,
  Redo,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Regex,
  Repeat,
  Repeat1,
  Repeat2,
  Replace,
  ReplaceAll,
  Reply,
  ReplyAll,
  Rewind,
  Rocket,
  RockingChair,
  RotateCcw,
  RotateCw,
  Router,
  Rows,
  Rss,
  Ruler,
  Save,
  SaveAll,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanFace,
  ScanLine,
  Scissors,
  ScreenShare,
  ScreenShareOff,
  ScrollText,
  SearchIcon,
  Send,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Settings2,
  Share,
  Share2,
  Sheet,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldQuestion,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Skull,
  Slack,
  Slash,
  Slice,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  SmartphoneCharging,
  Smile,
  SmilePlus,
  Snowflake,
  SortAsc,
  SortDesc,
  Sparkle,
  Sparkles,
  Speaker,
  Spline,
  Split,
  SplitSquareHorizontal,
  SplitSquareVertical,
  Sprout,
  Square,
  SquareStack,
  Star,
  StarHalf,
  StarOff,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  StopCircle,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Sun,
  SunMedium,
  Sunrise,
  Sunset,
  Superscript,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  Tablet,
  TabletSmartphone,
  Tag as TagIcon,
  Tags,
  Target,
  Tent,
  Terminal,
  TerminalSquare,
  TestTube,
  TestTube2,
  TestTubes,
  Text,
  TextCursor,
  TextCursorInput,
  TextQuote,
  TextSelect,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Touchpad,
  TouchpadOff,
  TowerControl,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Tv2,
  Twitch,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Undo,
  Undo2,
  Unlink,
  Unlink2,
  Unlock,
  UnlockKeyhole,
  Upload,
  UploadCloud,
  Usb,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Verified,
  Vibrate,
  VibrateOff,
  Video,
  VideoOff,
  View,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wallet2,
  WalletCards,
  Wand,
  Wand2,
  Warehouse,
  Watch,
  Waves,
  Webcam,
  Webhook,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  WrapText,
  Wrench,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { 
  SiBitcoin, 
  SiEthereum, 
  SiLitecoin, 
  SiMonero,
  SiGithub,
  SiGoogle,
  SiApple,
  SiLinux,
  SiDocker,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiPython,
  SiRust,
  SiGo,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiElasticsearch,
  SiStripe,
  SiPaypal,
  SiVisa,
  SiMastercard,
  SiSlack,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiX,
  SiLinkedin,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTwitch,
  SiSpotify,
  SiNetflix,
  SiAmazon,
  SiDropbox,
  SiNotion,
  SiFigma,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiDigitalocean,
  SiCloudflare,
  SiNginx,
  SiApache,
  SiJenkins,
  SiGitlab,
  SiBitbucket,
} from "react-icons/si";

interface IconItem {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  category: string;
  tags: string[];
}

const lucideIcons: IconItem[] = [
  { name: "Activity", icon: Activity, category: "Charts", tags: ["pulse", "monitor", "health"] },
  { name: "AlertCircle", icon: AlertCircle, category: "Alerts", tags: ["warning", "error", "info"] },
  { name: "AlertTriangle", icon: AlertTriangle, category: "Alerts", tags: ["warning", "caution", "danger"] },
  { name: "Anchor", icon: Anchor, category: "Objects", tags: ["ship", "marine", "dock"] },
  { name: "Archive", icon: Archive, category: "Files", tags: ["box", "storage", "backup"] },
  { name: "ArrowDown", icon: ArrowDown, category: "Arrows", tags: ["down", "direction", "navigate"] },
  { name: "ArrowDownUp", icon: ArrowDownUp, category: "Arrows", tags: ["sort", "swap", "exchange"] },
  { name: "ArrowLeft", icon: ArrowLeft, category: "Arrows", tags: ["left", "back", "previous"] },
  { name: "ArrowLeftRight", icon: ArrowLeftRight, category: "Arrows", tags: ["swap", "exchange", "transfer"] },
  { name: "ArrowRight", icon: ArrowRight, category: "Arrows", tags: ["right", "next", "forward"] },
  { name: "ArrowUp", icon: ArrowUp, category: "Arrows", tags: ["up", "direction", "navigate"] },
  { name: "ArrowUpDown", icon: ArrowUpDown, category: "Arrows", tags: ["sort", "swap", "exchange"] },
  { name: "AtSign", icon: AtSign, category: "Communication", tags: ["email", "mention", "at"] },
  { name: "Award", icon: Award, category: "Objects", tags: ["badge", "achievement", "medal"] },
  { name: "Ban", icon: Ban, category: "Actions", tags: ["block", "forbidden", "prohibited"] },
  { name: "BarChart", icon: BarChart, category: "Charts", tags: ["graph", "analytics", "statistics"] },
  { name: "BarChart2", icon: BarChart2, category: "Charts", tags: ["graph", "analytics", "statistics"] },
  { name: "BarChart3", icon: BarChart3, category: "Charts", tags: ["graph", "analytics", "horizontal"] },
  { name: "BarChart4", icon: BarChart4, category: "Charts", tags: ["graph", "analytics", "horizontal"] },
  { name: "Battery", icon: Battery, category: "Devices", tags: ["power", "energy", "charge"] },
  { name: "BatteryCharging", icon: BatteryCharging, category: "Devices", tags: ["power", "charging", "electricity"] },
  { name: "BatteryFull", icon: BatteryFull, category: "Devices", tags: ["power", "full", "complete"] },
  { name: "BatteryLow", icon: BatteryLow, category: "Devices", tags: ["power", "low", "warning"] },
  { name: "Bell", icon: Bell, category: "Notifications", tags: ["alert", "notification", "alarm"] },
  { name: "BellOff", icon: BellOff, category: "Notifications", tags: ["mute", "silent", "disable"] },
  { name: "BellRing", icon: BellRing, category: "Notifications", tags: ["alert", "ringing", "active"] },
  { name: "Bluetooth", icon: Bluetooth, category: "Connectivity", tags: ["wireless", "connect", "device"] },
  { name: "Bold", icon: Bold, category: "Text", tags: ["format", "strong", "weight"] },
  { name: "Book", icon: Book, category: "Objects", tags: ["read", "library", "education"] },
  { name: "BookOpen", icon: BookOpen, category: "Objects", tags: ["read", "open", "study"] },
  { name: "Bookmark", icon: Bookmark, category: "Actions", tags: ["save", "favorite", "mark"] },
  { name: "Box", icon: Box, category: "Objects", tags: ["package", "container", "cube"] },
  { name: "Briefcase", icon: Briefcase, category: "Objects", tags: ["work", "business", "job"] },
  { name: "Bug", icon: Bug, category: "Development", tags: ["error", "debug", "issue"] },
  { name: "Building", icon: Building, category: "Places", tags: ["office", "company", "business"] },
  { name: "Building2", icon: Building2, category: "Places", tags: ["office", "skyscraper", "city"] },
  { name: "Calendar", icon: Calendar, category: "Time", tags: ["date", "schedule", "event"] },
  { name: "CalendarDays", icon: CalendarDays, category: "Time", tags: ["date", "month", "schedule"] },
  { name: "Camera", icon: Camera, category: "Media", tags: ["photo", "picture", "capture"] },
  { name: "CameraOff", icon: CameraOff, category: "Media", tags: ["photo", "disabled", "privacy"] },
  { name: "Check", icon: Check, category: "Actions", tags: ["done", "complete", "success"] },
  { name: "CheckCircle", icon: CheckCircle, category: "Actions", tags: ["done", "success", "verified"] },
  { name: "CheckCircle2", icon: CheckCircle2, category: "Actions", tags: ["done", "success", "filled"] },
  { name: "CheckSquare", icon: CheckSquare, category: "Actions", tags: ["done", "checkbox", "complete"] },
  { name: "ChevronDown", icon: ChevronDown, category: "Arrows", tags: ["expand", "dropdown", "more"] },
  { name: "ChevronLeft", icon: ChevronLeft, category: "Arrows", tags: ["back", "previous", "left"] },
  { name: "ChevronRight", icon: ChevronRight, category: "Arrows", tags: ["next", "forward", "right"] },
  { name: "ChevronUp", icon: ChevronUp, category: "Arrows", tags: ["collapse", "up", "less"] },
  { name: "ChevronsDown", icon: ChevronsDown, category: "Arrows", tags: ["expand", "more", "down"] },
  { name: "ChevronsLeft", icon: ChevronsLeft, category: "Arrows", tags: ["first", "start", "rewind"] },
  { name: "ChevronsRight", icon: ChevronsRight, category: "Arrows", tags: ["last", "end", "forward"] },
  { name: "ChevronsUp", icon: ChevronsUp, category: "Arrows", tags: ["collapse", "top", "up"] },
  { name: "Circle", icon: Circle, category: "Shapes", tags: ["round", "dot", "shape"] },
  { name: "CircleDot", icon: CircleDot, category: "Shapes", tags: ["target", "center", "point"] },
  { name: "Clipboard", icon: Clipboard, category: "Actions", tags: ["copy", "paste", "notes"] },
  { name: "ClipboardCheck", icon: ClipboardCheck, category: "Actions", tags: ["done", "complete", "verified"] },
  { name: "ClipboardList", icon: ClipboardList, category: "Actions", tags: ["tasks", "todo", "list"] },
  { name: "Clock", icon: Clock, category: "Time", tags: ["time", "watch", "schedule"] },
  { name: "Cloud", icon: Cloud, category: "Weather", tags: ["storage", "sky", "online"] },
  { name: "CloudDownload", icon: CloudDownload, category: "Actions", tags: ["download", "sync", "cloud"] },
  { name: "CloudUpload", icon: CloudUpload, category: "Actions", tags: ["upload", "sync", "cloud"] },
  { name: "Code", icon: Code, category: "Development", tags: ["programming", "html", "brackets"] },
  { name: "Code2", icon: Code2, category: "Development", tags: ["programming", "script", "terminal"] },
  { name: "Cog", icon: Cog, category: "Settings", tags: ["gear", "settings", "configure"] },
  { name: "Coins", icon: Coins, category: "Finance", tags: ["money", "currency", "stack"] },
  { name: "Columns", icon: Columns, category: "Layout", tags: ["grid", "table", "columns"] },
  { name: "Command", icon: Command, category: "Keyboard", tags: ["cmd", "mac", "shortcut"] },
  { name: "Compass", icon: Compass, category: "Navigation", tags: ["direction", "explore", "navigate"] },
  { name: "Component", icon: Component, category: "Development", tags: ["module", "widget", "element"] },
  { name: "Contact", icon: Contact, category: "Communication", tags: ["person", "card", "address"] },
  { name: "Copy", icon: Copy, category: "Actions", tags: ["duplicate", "clipboard", "paste"] },
  { name: "CopyCheck", icon: CopyCheck, category: "Actions", tags: ["copied", "success", "done"] },
  { name: "CreditCard", icon: CreditCard, category: "Finance", tags: ["payment", "card", "money"] },
  { name: "Crop", icon: Crop, category: "Editing", tags: ["image", "resize", "cut"] },
  { name: "Crosshair", icon: Crosshair, category: "Navigation", tags: ["target", "aim", "focus"] },
  { name: "Crown", icon: Crown, category: "Objects", tags: ["king", "premium", "royal"] },
  { name: "Database", icon: Database, category: "Development", tags: ["storage", "data", "server"] },
  { name: "Delete", icon: Delete, category: "Actions", tags: ["remove", "backspace", "erase"] },
  { name: "Diamond", icon: Diamond, category: "Shapes", tags: ["gem", "premium", "valuable"] },
  { name: "DollarSign", icon: DollarSign, category: "Finance", tags: ["money", "currency", "price"] },
  { name: "Download", icon: Download, category: "Actions", tags: ["save", "export", "get"] },
  { name: "DownloadCloud", icon: DownloadCloud, category: "Actions", tags: ["cloud", "sync", "save"] },
  { name: "Droplet", icon: Droplet, category: "Objects", tags: ["water", "liquid", "drop"] },
  { name: "Edit", icon: Edit, category: "Actions", tags: ["modify", "write", "pencil"] },
  { name: "Edit2", icon: Edit2, category: "Actions", tags: ["modify", "pencil", "write"] },
  { name: "Edit3", icon: Edit3, category: "Actions", tags: ["modify", "pen", "write"] },
  { name: "ExternalLink", icon: ExternalLink, category: "Navigation", tags: ["open", "new", "external"] },
  { name: "Eye", icon: Eye, category: "Actions", tags: ["view", "see", "visible"] },
  { name: "EyeOff", icon: EyeOff, category: "Actions", tags: ["hide", "invisible", "private"] },
  { name: "File", icon: File, category: "Files", tags: ["document", "paper", "page"] },
  { name: "FileCheck", icon: FileCheck, category: "Files", tags: ["verified", "approved", "done"] },
  { name: "FileCode", icon: FileCode, category: "Files", tags: ["source", "programming", "script"] },
  { name: "FileJson", icon: FileJson, category: "Files", tags: ["data", "json", "config"] },
  { name: "FilePlus", icon: FilePlus, category: "Files", tags: ["new", "create", "add"] },
  { name: "FileSearch", icon: FileSearch, category: "Files", tags: ["find", "search", "look"] },
  { name: "FileText", icon: FileText, category: "Files", tags: ["document", "text", "content"] },
  { name: "FileWarning", icon: FileWarning, category: "Files", tags: ["error", "alert", "problem"] },
  { name: "FileX", icon: FileX, category: "Files", tags: ["delete", "remove", "error"] },
  { name: "Filter", icon: Filter, category: "Actions", tags: ["sort", "filter", "funnel"] },
  { name: "FilterX", icon: FilterX, category: "Actions", tags: ["clear", "remove", "reset"] },
  { name: "Flag", icon: Flag, category: "Objects", tags: ["mark", "report", "country"] },
  { name: "Flame", icon: Flame, category: "Objects", tags: ["fire", "hot", "trending"] },
  { name: "Folder", icon: Folder, category: "Files", tags: ["directory", "folder", "organize"] },
  { name: "FolderOpen", icon: FolderOpen, category: "Files", tags: ["directory", "open", "browse"] },
  { name: "FolderPlus", icon: FolderPlus, category: "Files", tags: ["new", "create", "add"] },
  { name: "Forward", icon: Forward, category: "Actions", tags: ["send", "share", "email"] },
  { name: "Frown", icon: Frown, category: "Emoji", tags: ["sad", "unhappy", "face"] },
  { name: "Gauge", icon: Gauge, category: "Charts", tags: ["speed", "meter", "dashboard"] },
  { name: "Gift", icon: Gift, category: "Objects", tags: ["present", "reward", "surprise"] },
  { name: "GitBranch", icon: GitBranch, category: "Development", tags: ["version", "branch", "git"] },
  { name: "GitCommit", icon: GitCommit, category: "Development", tags: ["version", "commit", "save"] },
  { name: "GitCompare", icon: GitCompare, category: "Development", tags: ["diff", "compare", "merge"] },
  { name: "GitFork", icon: GitFork, category: "Development", tags: ["fork", "copy", "clone"] },
  { name: "GitMerge", icon: GitMerge, category: "Development", tags: ["merge", "combine", "join"] },
  { name: "GitPullRequest", icon: GitPullRequest, category: "Development", tags: ["pr", "review", "merge"] },
  { name: "Globe", icon: Globe, category: "Navigation", tags: ["world", "web", "internet"] },
  { name: "Globe2", icon: Globe2, category: "Navigation", tags: ["world", "earth", "global"] },
  { name: "GraduationCap", icon: GraduationCap, category: "Objects", tags: ["education", "school", "learn"] },
  { name: "Grid", icon: Grid, category: "Layout", tags: ["layout", "table", "squares"] },
  { name: "Grid2X2", icon: Grid2X2, category: "Layout", tags: ["layout", "grid", "2x2"] },
  { name: "Grid3X3", icon: Grid3X3, category: "Layout", tags: ["layout", "grid", "3x3"] },
  { name: "Grip", icon: Grip, category: "Actions", tags: ["drag", "handle", "move"] },
  { name: "GripHorizontal", icon: GripHorizontal, category: "Actions", tags: ["drag", "handle", "horizontal"] },
  { name: "GripVertical", icon: GripVertical, category: "Actions", tags: ["drag", "handle", "vertical"] },
  { name: "Hammer", icon: Hammer, category: "Objects", tags: ["tool", "build", "construct"] },
  { name: "Hand", icon: Hand, category: "Gestures", tags: ["stop", "wave", "palm"] },
  { name: "HardDrive", icon: HardDrive, category: "Devices", tags: ["storage", "disk", "data"] },
  { name: "Hash", icon: Hash, category: "Objects", tags: ["hashtag", "number", "pound"] },
  { name: "Headphones", icon: Headphones, category: "Devices", tags: ["audio", "music", "listen"] },
  { name: "Heart", icon: Heart, category: "Actions", tags: ["like", "love", "favorite"] },
  { name: "HeartOff", icon: HeartOff, category: "Actions", tags: ["unlike", "dislike", "remove"] },
  { name: "HelpCircle", icon: HelpCircle, category: "Alerts", tags: ["question", "help", "info"] },
  { name: "Hexagon", icon: Hexagon, category: "Shapes", tags: ["shape", "polygon", "6"] },
  { name: "History", icon: History, category: "Time", tags: ["past", "undo", "time"] },
  { name: "Home", icon: Home, category: "Navigation", tags: ["house", "main", "dashboard"] },
  { name: "Image", icon: Image, category: "Media", tags: ["photo", "picture", "gallery"] },
  { name: "ImageOff", icon: ImageOff, category: "Media", tags: ["broken", "missing", "placeholder"] },
  { name: "ImagePlus", icon: ImagePlus, category: "Media", tags: ["add", "upload", "new"] },
  { name: "Import", icon: Import, category: "Actions", tags: ["upload", "bring", "load"] },
  { name: "Inbox", icon: Inbox, category: "Communication", tags: ["mail", "receive", "messages"] },
  { name: "Infinity", icon: Infinity, category: "Shapes", tags: ["forever", "loop", "unlimited"] },
  { name: "Info", icon: Info, category: "Alerts", tags: ["information", "help", "about"] },
  { name: "Key", icon: Key, category: "Security", tags: ["password", "lock", "access"] },
  { name: "Keyboard", icon: Keyboard, category: "Devices", tags: ["type", "input", "keys"] },
  { name: "Landmark", icon: Landmark, category: "Finance", tags: ["bank", "building", "institution"] },
  { name: "Languages", icon: Languages, category: "Objects", tags: ["translate", "language", "i18n"] },
  { name: "Laptop", icon: Laptop, category: "Devices", tags: ["computer", "device", "screen"] },
  { name: "Laptop2", icon: Laptop2, category: "Devices", tags: ["computer", "notebook", "pc"] },
  { name: "Layers", icon: Layers, category: "Layout", tags: ["stack", "levels", "design"] },
  { name: "Layout", icon: Layout, category: "Layout", tags: ["template", "design", "page"] },
  { name: "LayoutDashboard", icon: LayoutDashboard, category: "Layout", tags: ["dashboard", "home", "overview"] },
  { name: "LayoutGrid", icon: LayoutGrid, category: "Layout", tags: ["grid", "tiles", "gallery"] },
  { name: "LayoutList", icon: LayoutList, category: "Layout", tags: ["list", "rows", "table"] },
  { name: "Leaf", icon: Leaf, category: "Nature", tags: ["plant", "eco", "green"] },
  { name: "Library", icon: Library, category: "Objects", tags: ["books", "collection", "archive"] },
  { name: "LifeBuoy", icon: LifeBuoy, category: "Objects", tags: ["help", "support", "rescue"] },
  { name: "Lightbulb", icon: Lightbulb, category: "Objects", tags: ["idea", "light", "tip"] },
  { name: "LightbulbOff", icon: LightbulbOff, category: "Objects", tags: ["dark", "off", "idea"] },
  { name: "LineChart", icon: LineChart, category: "Charts", tags: ["graph", "trend", "analytics"] },
  { name: "Link", icon: Link, category: "Actions", tags: ["url", "chain", "connect"] },
  { name: "Link2", icon: Link2, category: "Actions", tags: ["url", "hyperlink", "chain"] },
  { name: "Link2Off", icon: Link2Off, category: "Actions", tags: ["unlink", "break", "disconnect"] },
  { name: "List", icon: List, category: "Layout", tags: ["menu", "items", "bullets"] },
  { name: "ListChecks", icon: ListChecks, category: "Layout", tags: ["todo", "tasks", "complete"] },
  { name: "ListFilter", icon: ListFilter, category: "Layout", tags: ["filter", "sort", "organize"] },
  { name: "ListOrdered", icon: ListOrdered, category: "Layout", tags: ["numbered", "order", "sequence"] },
  { name: "ListPlus", icon: ListPlus, category: "Layout", tags: ["add", "new", "create"] },
  { name: "ListTodo", icon: ListTodo, category: "Layout", tags: ["tasks", "checkbox", "todo"] },
  { name: "Loader", icon: Loader, category: "Actions", tags: ["loading", "spinner", "wait"] },
  { name: "Loader2", icon: Loader2, category: "Actions", tags: ["loading", "spinner", "animated"] },
  { name: "Locate", icon: Locate, category: "Navigation", tags: ["location", "gps", "find"] },
  { name: "LocateFixed", icon: LocateFixed, category: "Navigation", tags: ["location", "fixed", "gps"] },
  { name: "Lock", icon: Lock, category: "Security", tags: ["secure", "locked", "private"] },
  { name: "LockKeyhole", icon: LockKeyhole, category: "Security", tags: ["secure", "password", "private"] },
  { name: "LogIn", icon: LogIn, category: "Actions", tags: ["signin", "login", "enter"] },
  { name: "LogOut", icon: LogOut, category: "Actions", tags: ["signout", "logout", "exit"] },
  { name: "Mail", icon: Mail, category: "Communication", tags: ["email", "message", "envelope"] },
  { name: "MailCheck", icon: MailCheck, category: "Communication", tags: ["email", "verified", "sent"] },
  { name: "MailOpen", icon: MailOpen, category: "Communication", tags: ["email", "read", "opened"] },
  { name: "MailPlus", icon: MailPlus, category: "Communication", tags: ["email", "new", "compose"] },
  { name: "Map", icon: Map, category: "Navigation", tags: ["location", "directions", "geography"] },
  { name: "MapPin", icon: MapPin, category: "Navigation", tags: ["location", "marker", "place"] },
  { name: "MapPinOff", icon: MapPinOff, category: "Navigation", tags: ["location", "remove", "hide"] },
  { name: "Maximize", icon: Maximize, category: "Actions", tags: ["expand", "fullscreen", "enlarge"] },
  { name: "Maximize2", icon: Maximize2, category: "Actions", tags: ["expand", "arrows", "fullscreen"] },
  { name: "Megaphone", icon: Megaphone, category: "Communication", tags: ["announce", "broadcast", "marketing"] },
  { name: "Meh", icon: Meh, category: "Emoji", tags: ["neutral", "face", "okay"] },
  { name: "Menu", icon: Menu, category: "Navigation", tags: ["hamburger", "lines", "nav"] },
  { name: "MessageCircle", icon: MessageCircle, category: "Communication", tags: ["chat", "comment", "bubble"] },
  { name: "MessageSquare", icon: MessageSquare, category: "Communication", tags: ["chat", "comment", "message"] },
  { name: "Mic", icon: Mic, category: "Media", tags: ["microphone", "audio", "record"] },
  { name: "MicOff", icon: MicOff, category: "Media", tags: ["mute", "disabled", "silent"] },
  { name: "Minimize", icon: Minimize, category: "Actions", tags: ["shrink", "reduce", "collapse"] },
  { name: "Minimize2", icon: Minimize2, category: "Actions", tags: ["shrink", "arrows", "collapse"] },
  { name: "Minus", icon: Minus, category: "Actions", tags: ["subtract", "remove", "negative"] },
  { name: "MinusCircle", icon: MinusCircle, category: "Actions", tags: ["remove", "delete", "subtract"] },
  { name: "MinusSquare", icon: MinusSquare, category: "Actions", tags: ["remove", "collapse", "subtract"] },
  { name: "Monitor", icon: Monitor, category: "Devices", tags: ["screen", "display", "computer"] },
  { name: "MonitorOff", icon: MonitorOff, category: "Devices", tags: ["screen", "off", "disabled"] },
  { name: "Moon", icon: Moon, category: "Theme", tags: ["dark", "night", "mode"] },
  { name: "MoreHorizontal", icon: MoreHorizontal, category: "Actions", tags: ["menu", "options", "dots"] },
  { name: "MoreVertical", icon: MoreVertical, category: "Actions", tags: ["menu", "options", "kebab"] },
  { name: "Mountain", icon: Mountain, category: "Nature", tags: ["peak", "landscape", "hiking"] },
  { name: "MousePointer", icon: MousePointer, category: "Devices", tags: ["cursor", "click", "select"] },
  { name: "MousePointer2", icon: MousePointer2, category: "Devices", tags: ["cursor", "arrow", "select"] },
  { name: "MousePointerClick", icon: MousePointerClick, category: "Devices", tags: ["cursor", "click", "action"] },
  { name: "Move", icon: Move, category: "Actions", tags: ["drag", "reposition", "arrows"] },
  { name: "MoveHorizontal", icon: MoveHorizontal, category: "Actions", tags: ["drag", "horizontal", "resize"] },
  { name: "MoveVertical", icon: MoveVertical, category: "Actions", tags: ["drag", "vertical", "resize"] },
  { name: "Music", icon: Music, category: "Media", tags: ["audio", "song", "note"] },
  { name: "Music2", icon: Music2, category: "Media", tags: ["audio", "notes", "song"] },
  { name: "Navigation", icon: Navigation, category: "Navigation", tags: ["arrow", "direction", "gps"] },
  { name: "Navigation2", icon: Navigation2, category: "Navigation", tags: ["arrow", "location", "gps"] },
  { name: "Network", icon: Network, category: "Connectivity", tags: ["nodes", "connected", "graph"] },
  { name: "Newspaper", icon: Newspaper, category: "Objects", tags: ["news", "article", "press"] },
  { name: "Octagon", icon: Octagon, category: "Shapes", tags: ["stop", "shape", "8"] },
  { name: "Package", icon: Package, category: "Objects", tags: ["box", "delivery", "shipping"] },
  { name: "Package2", icon: Package2, category: "Objects", tags: ["box", "open", "unpack"] },
  { name: "PackageCheck", icon: PackageCheck, category: "Objects", tags: ["delivered", "verified", "done"] },
  { name: "PackageOpen", icon: PackageOpen, category: "Objects", tags: ["unpack", "open", "reveal"] },
  { name: "PackagePlus", icon: PackagePlus, category: "Objects", tags: ["add", "new", "create"] },
  { name: "PackageSearch", icon: PackageSearch, category: "Objects", tags: ["find", "track", "search"] },
  { name: "Paintbrush", icon: Paintbrush, category: "Editing", tags: ["paint", "draw", "design"] },
  { name: "Paintbrush2", icon: Paintbrush2, category: "Editing", tags: ["paint", "art", "brush"] },
  { name: "Palette", icon: Palette, category: "Editing", tags: ["colors", "theme", "design"] },
  { name: "Paperclip", icon: Paperclip, category: "Actions", tags: ["attach", "file", "link"] },
  { name: "Pause", icon: Pause, category: "Media", tags: ["stop", "hold", "wait"] },
  { name: "PauseCircle", icon: PauseCircle, category: "Media", tags: ["stop", "player", "hold"] },
  { name: "Pencil", icon: Pencil, category: "Actions", tags: ["edit", "write", "draw"] },
  { name: "Percent", icon: Percent, category: "Finance", tags: ["discount", "percentage", "rate"] },
  { name: "Phone", icon: Phone, category: "Communication", tags: ["call", "mobile", "contact"] },
  { name: "PhoneCall", icon: PhoneCall, category: "Communication", tags: ["calling", "ringing", "active"] },
  { name: "PhoneOff", icon: PhoneOff, category: "Communication", tags: ["hangup", "end", "disconnect"] },
  { name: "PieChart", icon: PieChart, category: "Charts", tags: ["graph", "analytics", "statistics"] },
  { name: "PiggyBank", icon: PiggyBank, category: "Finance", tags: ["savings", "money", "bank"] },
  { name: "Pin", icon: Pin, category: "Actions", tags: ["attach", "mark", "sticky"] },
  { name: "PinOff", icon: PinOff, category: "Actions", tags: ["unpin", "remove", "detach"] },
  { name: "Pizza", icon: Pizza, category: "Objects", tags: ["food", "slice", "eat"] },
  { name: "Plane", icon: Plane, category: "Objects", tags: ["flight", "travel", "airplane"] },
  { name: "Play", icon: Play, category: "Media", tags: ["start", "video", "music"] },
  { name: "PlayCircle", icon: PlayCircle, category: "Media", tags: ["start", "player", "video"] },
  { name: "Plug", icon: Plug, category: "Devices", tags: ["power", "connect", "electricity"] },
  { name: "Plug2", icon: Plug2, category: "Devices", tags: ["connect", "integration", "power"] },
  { name: "PlugZap", icon: PlugZap, category: "Devices", tags: ["power", "electricity", "charge"] },
  { name: "Plus", icon: Plus, category: "Actions", tags: ["add", "new", "create"] },
  { name: "PlusCircle", icon: PlusCircle, category: "Actions", tags: ["add", "create", "new"] },
  { name: "PlusSquare", icon: PlusSquare, category: "Actions", tags: ["add", "expand", "new"] },
  { name: "Pocket", icon: Pocket, category: "Actions", tags: ["save", "bookmark", "later"] },
  { name: "Podcast", icon: Podcast, category: "Media", tags: ["audio", "show", "episode"] },
  { name: "Power", icon: Power, category: "Devices", tags: ["on", "off", "button"] },
  { name: "PowerOff", icon: PowerOff, category: "Devices", tags: ["shutdown", "off", "exit"] },
  { name: "Printer", icon: Printer, category: "Devices", tags: ["print", "paper", "document"] },
  { name: "Puzzle", icon: Puzzle, category: "Objects", tags: ["piece", "plugin", "extension"] },
  { name: "QrCode", icon: QrCode, category: "Objects", tags: ["scan", "code", "barcode"] },
  { name: "Quote", icon: Quote, category: "Text", tags: ["citation", "blockquote", "text"] },
  { name: "Radio", icon: Radio, category: "Media", tags: ["broadcast", "audio", "fm"] },
  { name: "Redo", icon: Redo, category: "Actions", tags: ["forward", "again", "repeat"] },
  { name: "Redo2", icon: Redo2, category: "Actions", tags: ["forward", "redo", "repeat"] },
  { name: "RefreshCcw", icon: RefreshCcw, category: "Actions", tags: ["reload", "sync", "update"] },
  { name: "RefreshCw", icon: RefreshCw, category: "Actions", tags: ["reload", "sync", "clockwise"] },
  { name: "Repeat", icon: Repeat, category: "Actions", tags: ["loop", "cycle", "again"] },
  { name: "Repeat1", icon: Repeat1, category: "Actions", tags: ["loop", "single", "once"] },
  { name: "Repeat2", icon: Repeat2, category: "Actions", tags: ["loop", "cycle", "repeat"] },
  { name: "Reply", icon: Reply, category: "Communication", tags: ["respond", "answer", "back"] },
  { name: "ReplyAll", icon: ReplyAll, category: "Communication", tags: ["respond", "everyone", "all"] },
  { name: "Rocket", icon: Rocket, category: "Objects", tags: ["launch", "startup", "fast"] },
  { name: "RotateCcw", icon: RotateCcw, category: "Actions", tags: ["rotate", "left", "undo"] },
  { name: "RotateCw", icon: RotateCw, category: "Actions", tags: ["rotate", "right", "redo"] },
  { name: "Router", icon: Router, category: "Devices", tags: ["wifi", "network", "internet"] },
  { name: "Rows", icon: Rows, category: "Layout", tags: ["horizontal", "lines", "list"] },
  { name: "Rss", icon: Rss, category: "Communication", tags: ["feed", "blog", "subscribe"] },
  { name: "Ruler", icon: Ruler, category: "Objects", tags: ["measure", "size", "length"] },
  { name: "Save", icon: Save, category: "Actions", tags: ["floppy", "disk", "store"] },
  { name: "SaveAll", icon: SaveAll, category: "Actions", tags: ["save", "multiple", "all"] },
  { name: "Scale", icon: Scale, category: "Objects", tags: ["balance", "weight", "measure"] },
  { name: "Scan", icon: Scan, category: "Actions", tags: ["barcode", "qr", "read"] },
  { name: "ScanFace", icon: ScanFace, category: "Actions", tags: ["face", "recognition", "id"] },
  { name: "ScanLine", icon: ScanLine, category: "Actions", tags: ["barcode", "scan", "read"] },
  { name: "Scissors", icon: Scissors, category: "Actions", tags: ["cut", "trim", "edit"] },
  { name: "ScreenShare", icon: ScreenShare, category: "Media", tags: ["present", "share", "display"] },
  { name: "ScreenShareOff", icon: ScreenShareOff, category: "Media", tags: ["stop", "hide", "private"] },
  { name: "Search", icon: Search, category: "Actions", tags: ["find", "look", "magnify"] },
  { name: "Send", icon: Send, category: "Communication", tags: ["message", "submit", "paper"] },
  { name: "Server", icon: Server, category: "Development", tags: ["host", "database", "backend"] },
  { name: "ServerCog", icon: ServerCog, category: "Development", tags: ["configure", "settings", "admin"] },
  { name: "ServerCrash", icon: ServerCrash, category: "Development", tags: ["error", "down", "offline"] },
  { name: "ServerOff", icon: ServerOff, category: "Development", tags: ["offline", "disabled", "down"] },
  { name: "Settings", icon: Settings, category: "Settings", tags: ["gear", "configure", "options"] },
  { name: "Settings2", icon: Settings2, category: "Settings", tags: ["sliders", "configure", "adjust"] },
  { name: "Share", icon: Share, category: "Actions", tags: ["social", "send", "export"] },
  { name: "Share2", icon: Share2, category: "Actions", tags: ["network", "connect", "nodes"] },
  { name: "Sheet", icon: Sheet, category: "Files", tags: ["spreadsheet", "table", "excel"] },
  { name: "Shield", icon: Shield, category: "Security", tags: ["protect", "safe", "guard"] },
  { name: "ShieldAlert", icon: ShieldAlert, category: "Security", tags: ["warning", "alert", "danger"] },
  { name: "ShieldCheck", icon: ShieldCheck, category: "Security", tags: ["verified", "safe", "protected"] },
  { name: "ShieldOff", icon: ShieldOff, category: "Security", tags: ["unprotected", "vulnerable", "disabled"] },
  { name: "ShoppingBag", icon: ShoppingBag, category: "Commerce", tags: ["shop", "bag", "purchase"] },
  { name: "ShoppingCart", icon: ShoppingCart, category: "Commerce", tags: ["cart", "buy", "checkout"] },
  { name: "Shuffle", icon: Shuffle, category: "Media", tags: ["random", "mix", "shuffle"] },
  { name: "Signal", icon: Signal, category: "Connectivity", tags: ["strength", "network", "bars"] },
  { name: "SignalHigh", icon: SignalHigh, category: "Connectivity", tags: ["strong", "full", "network"] },
  { name: "SignalLow", icon: SignalLow, category: "Connectivity", tags: ["weak", "low", "network"] },
  { name: "SignalMedium", icon: SignalMedium, category: "Connectivity", tags: ["medium", "network", "signal"] },
  { name: "SignalZero", icon: SignalZero, category: "Connectivity", tags: ["none", "offline", "no signal"] },
  { name: "Sliders", icon: Sliders, category: "Settings", tags: ["adjust", "control", "settings"] },
  { name: "SlidersHorizontal", icon: SlidersHorizontal, category: "Settings", tags: ["adjust", "horizontal", "settings"] },
  { name: "Smartphone", icon: Smartphone, category: "Devices", tags: ["phone", "mobile", "device"] },
  { name: "SmartphoneCharging", icon: SmartphoneCharging, category: "Devices", tags: ["phone", "charging", "battery"] },
  { name: "Smile", icon: Smile, category: "Emoji", tags: ["happy", "face", "emoji"] },
  { name: "SmilePlus", icon: SmilePlus, category: "Emoji", tags: ["add", "reaction", "emoji"] },
  { name: "Snowflake", icon: Snowflake, category: "Weather", tags: ["cold", "winter", "freeze"] },
  { name: "SortAsc", icon: SortAsc, category: "Actions", tags: ["ascending", "order", "a-z"] },
  { name: "SortDesc", icon: SortDesc, category: "Actions", tags: ["descending", "order", "z-a"] },
  { name: "Sparkle", icon: Sparkle, category: "Objects", tags: ["star", "magic", "new"] },
  { name: "Sparkles", icon: Sparkles, category: "Objects", tags: ["magic", "ai", "special"] },
  { name: "Speaker", icon: Speaker, category: "Media", tags: ["audio", "sound", "volume"] },
  { name: "Split", icon: Split, category: "Actions", tags: ["divide", "fork", "branch"] },
  { name: "Sprout", icon: Sprout, category: "Nature", tags: ["plant", "grow", "eco"] },
  { name: "Square", icon: Square, category: "Shapes", tags: ["box", "shape", "empty"] },
  { name: "SquareStack", icon: SquareStack, category: "Layout", tags: ["layers", "stack", "multiple"] },
  { name: "Star", icon: Star, category: "Actions", tags: ["favorite", "rate", "bookmark"] },
  { name: "StarHalf", icon: StarHalf, category: "Actions", tags: ["rating", "half", "partial"] },
  { name: "StarOff", icon: StarOff, category: "Actions", tags: ["unfavorite", "remove", "unstar"] },
  { name: "Stethoscope", icon: Stethoscope, category: "Objects", tags: ["health", "medical", "doctor"] },
  { name: "StickyNote", icon: StickyNote, category: "Objects", tags: ["note", "memo", "post-it"] },
  { name: "StopCircle", icon: StopCircle, category: "Media", tags: ["stop", "halt", "end"] },
  { name: "Store", icon: Store, category: "Commerce", tags: ["shop", "market", "retail"] },
  { name: "Strikethrough", icon: Strikethrough, category: "Text", tags: ["format", "delete", "cross"] },
  { name: "Sun", icon: Sun, category: "Theme", tags: ["light", "day", "bright"] },
  { name: "SunMedium", icon: SunMedium, category: "Weather", tags: ["light", "bright", "medium"] },
  { name: "Sunrise", icon: Sunrise, category: "Weather", tags: ["morning", "dawn", "day"] },
  { name: "Sunset", icon: Sunset, category: "Weather", tags: ["evening", "dusk", "night"] },
  { name: "Table", icon: Table, category: "Layout", tags: ["grid", "data", "spreadsheet"] },
  { name: "Table2", icon: Table2, category: "Layout", tags: ["data", "grid", "rows"] },
  { name: "Tablet", icon: Tablet, category: "Devices", tags: ["ipad", "device", "screen"] },
  { name: "Tag", icon: TagIcon, category: "Objects", tags: ["label", "price", "category"] },
  { name: "Tags", icon: Tags, category: "Objects", tags: ["labels", "multiple", "categories"] },
  { name: "Target", icon: Target, category: "Objects", tags: ["goal", "aim", "focus"] },
  { name: "Terminal", icon: Terminal, category: "Development", tags: ["console", "command", "cli"] },
  { name: "TerminalSquare", icon: TerminalSquare, category: "Development", tags: ["console", "code", "shell"] },
  { name: "TestTube", icon: TestTube, category: "Objects", tags: ["science", "lab", "experiment"] },
  { name: "TestTube2", icon: TestTube2, category: "Objects", tags: ["science", "chemistry", "test"] },
  { name: "Text", icon: Text, category: "Text", tags: ["content", "paragraph", "write"] },
  { name: "TextCursor", icon: TextCursor, category: "Text", tags: ["input", "cursor", "type"] },
  { name: "TextCursorInput", icon: TextCursorInput, category: "Text", tags: ["input", "field", "text"] },
  { name: "Thermometer", icon: Thermometer, category: "Objects", tags: ["temperature", "weather", "heat"] },
  { name: "ThumbsDown", icon: ThumbsDown, category: "Actions", tags: ["dislike", "no", "bad"] },
  { name: "ThumbsUp", icon: ThumbsUp, category: "Actions", tags: ["like", "yes", "good"] },
  { name: "Ticket", icon: Ticket, category: "Objects", tags: ["event", "pass", "coupon"] },
  { name: "Timer", icon: Timer, category: "Time", tags: ["stopwatch", "countdown", "clock"] },
  { name: "TimerOff", icon: TimerOff, category: "Time", tags: ["stop", "pause", "off"] },
  { name: "TimerReset", icon: TimerReset, category: "Time", tags: ["restart", "reset", "clear"] },
  { name: "ToggleLeft", icon: ToggleLeft, category: "Actions", tags: ["switch", "off", "disable"] },
  { name: "ToggleRight", icon: ToggleRight, category: "Actions", tags: ["switch", "on", "enable"] },
  { name: "Trash", icon: Trash, category: "Actions", tags: ["delete", "remove", "bin"] },
  { name: "Trash2", icon: Trash2, category: "Actions", tags: ["delete", "remove", "garbage"] },
  { name: "TrendingDown", icon: TrendingDown, category: "Charts", tags: ["decrease", "fall", "down"] },
  { name: "TrendingUp", icon: TrendingUp, category: "Charts", tags: ["increase", "rise", "up"] },
  { name: "Triangle", icon: Triangle, category: "Shapes", tags: ["shape", "warning", "alert"] },
  { name: "Trophy", icon: Trophy, category: "Objects", tags: ["award", "winner", "prize"] },
  { name: "Truck", icon: Truck, category: "Objects", tags: ["delivery", "shipping", "transport"] },
  { name: "Tv", icon: Tv, category: "Devices", tags: ["television", "screen", "monitor"] },
  { name: "Tv2", icon: Tv2, category: "Devices", tags: ["television", "display", "smart tv"] },
  { name: "Type", icon: Type, category: "Text", tags: ["font", "typography", "text"] },
  { name: "Umbrella", icon: Umbrella, category: "Objects", tags: ["rain", "weather", "protection"] },
  { name: "Underline", icon: Underline, category: "Text", tags: ["format", "text", "style"] },
  { name: "Undo", icon: Undo, category: "Actions", tags: ["back", "reverse", "cancel"] },
  { name: "Undo2", icon: Undo2, category: "Actions", tags: ["back", "undo", "reverse"] },
  { name: "Unlink", icon: Unlink, category: "Actions", tags: ["disconnect", "break", "remove"] },
  { name: "Unlink2", icon: Unlink2, category: "Actions", tags: ["disconnect", "unchain", "break"] },
  { name: "Unlock", icon: Unlock, category: "Security", tags: ["open", "access", "unlocked"] },
  { name: "UnlockKeyhole", icon: UnlockKeyhole, category: "Security", tags: ["open", "access", "key"] },
  { name: "Upload", icon: Upload, category: "Actions", tags: ["send", "import", "up"] },
  { name: "UploadCloud", icon: UploadCloud, category: "Actions", tags: ["cloud", "sync", "upload"] },
  { name: "Usb", icon: Usb, category: "Devices", tags: ["port", "connect", "drive"] },
  { name: "User", icon: User, category: "Users", tags: ["person", "account", "profile"] },
  { name: "UserCheck", icon: UserCheck, category: "Users", tags: ["verified", "approved", "confirm"] },
  { name: "UserCog", icon: UserCog, category: "Users", tags: ["settings", "admin", "configure"] },
  { name: "UserMinus", icon: UserMinus, category: "Users", tags: ["remove", "delete", "unfollow"] },
  { name: "UserPlus", icon: UserPlus, category: "Users", tags: ["add", "new", "follow"] },
  { name: "UserX", icon: UserX, category: "Users", tags: ["remove", "blocked", "delete"] },
  { name: "Users", icon: Users, category: "Users", tags: ["people", "group", "team"] },
  { name: "Vault", icon: Vault, category: "Security", tags: ["safe", "secure", "storage"] },
  { name: "Verified", icon: Verified, category: "Actions", tags: ["check", "approved", "badge"] },
  { name: "Video", icon: Video, category: "Media", tags: ["camera", "movie", "record"] },
  { name: "VideoOff", icon: VideoOff, category: "Media", tags: ["disabled", "camera", "off"] },
  { name: "View", icon: View, category: "Actions", tags: ["eye", "see", "display"] },
  { name: "Volume", icon: Volume, category: "Media", tags: ["sound", "audio", "speaker"] },
  { name: "Volume1", icon: Volume1, category: "Media", tags: ["sound", "low", "quiet"] },
  { name: "Volume2", icon: Volume2, category: "Media", tags: ["sound", "loud", "high"] },
  { name: "VolumeX", icon: VolumeX, category: "Media", tags: ["mute", "silent", "off"] },
  { name: "Wallet", icon: Wallet, category: "Finance", tags: ["money", "payment", "cards"] },
  { name: "Wallet2", icon: Wallet2, category: "Finance", tags: ["money", "billfold", "cash"] },
  { name: "WalletCards", icon: WalletCards, category: "Finance", tags: ["cards", "payment", "credit"] },
  { name: "Wand", icon: Wand, category: "Objects", tags: ["magic", "tool", "create"] },
  { name: "Wand2", icon: Wand2, category: "Objects", tags: ["magic", "sparkle", "ai"] },
  { name: "Warehouse", icon: Warehouse, category: "Places", tags: ["storage", "building", "inventory"] },
  { name: "Watch", icon: Watch, category: "Devices", tags: ["time", "wrist", "clock"] },
  { name: "Waves", icon: Waves, category: "Objects", tags: ["water", "ocean", "sound"] },
  { name: "Webcam", icon: Webcam, category: "Devices", tags: ["camera", "video", "stream"] },
  { name: "Webhook", icon: Webhook, category: "Development", tags: ["api", "integration", "hook"] },
  { name: "Wifi", icon: Wifi, category: "Connectivity", tags: ["wireless", "internet", "network"] },
  { name: "WifiOff", icon: WifiOff, category: "Connectivity", tags: ["offline", "disconnected", "no wifi"] },
  { name: "Wind", icon: Wind, category: "Weather", tags: ["air", "breeze", "weather"] },
  { name: "Wine", icon: Wine, category: "Objects", tags: ["drink", "glass", "celebration"] },
  { name: "WrapText", icon: WrapText, category: "Text", tags: ["wrap", "format", "text"] },
  { name: "Wrench", icon: Wrench, category: "Objects", tags: ["tool", "fix", "settings"] },
  { name: "X", icon: X, category: "Actions", tags: ["close", "cancel", "remove"] },
  { name: "XCircle", icon: XCircle, category: "Actions", tags: ["close", "cancel", "error"] },
  { name: "XOctagon", icon: XOctagon, category: "Actions", tags: ["stop", "error", "blocked"] },
  { name: "XSquare", icon: XSquare, category: "Actions", tags: ["close", "cancel", "remove"] },
  { name: "Zap", icon: Zap, category: "Objects", tags: ["lightning", "fast", "energy"] },
  { name: "ZapOff", icon: ZapOff, category: "Objects", tags: ["disabled", "off", "slow"] },
  { name: "ZoomIn", icon: ZoomIn, category: "Actions", tags: ["magnify", "enlarge", "bigger"] },
  { name: "ZoomOut", icon: ZoomOut, category: "Actions", tags: ["shrink", "reduce", "smaller"] },
];

const brandIcons: IconItem[] = [
  { name: "SiBitcoin", icon: SiBitcoin, category: "Crypto", tags: ["btc", "cryptocurrency", "coin"] },
  { name: "SiEthereum", icon: SiEthereum, category: "Crypto", tags: ["eth", "cryptocurrency", "coin"] },
  { name: "SiLitecoin", icon: SiLitecoin, category: "Crypto", tags: ["ltc", "cryptocurrency", "coin"] },
  { name: "SiMonero", icon: SiMonero, category: "Crypto", tags: ["xmr", "cryptocurrency", "privacy"] },
  { name: "SiGithub", icon: SiGithub, category: "Development", tags: ["git", "code", "repository"] },
  { name: "SiGoogle", icon: SiGoogle, category: "Companies", tags: ["search", "alphabet", "tech"] },
  { name: "SiApple", icon: SiApple, category: "Companies", tags: ["mac", "ios", "tech"] },
  { name: "SiLinux", icon: SiLinux, category: "Development", tags: ["os", "tux", "open source"] },
  { name: "SiDocker", icon: SiDocker, category: "Development", tags: ["container", "devops", "deploy"] },
  { name: "SiReact", icon: SiReact, category: "Development", tags: ["frontend", "javascript", "ui"] },
  { name: "SiTypescript", icon: SiTypescript, category: "Development", tags: ["ts", "types", "javascript"] },
  { name: "SiJavascript", icon: SiJavascript, category: "Development", tags: ["js", "web", "frontend"] },
  { name: "SiNodedotjs", icon: SiNodedotjs, category: "Development", tags: ["node", "backend", "server"] },
  { name: "SiPython", icon: SiPython, category: "Development", tags: ["py", "scripting", "ml"] },
  { name: "SiRust", icon: SiRust, category: "Development", tags: ["systems", "memory", "performance"] },
  { name: "SiGo", icon: SiGo, category: "Development", tags: ["golang", "backend", "cloud"] },
  { name: "SiPostgresql", icon: SiPostgresql, category: "Databases", tags: ["sql", "database", "relational"] },
  { name: "SiMongodb", icon: SiMongodb, category: "Databases", tags: ["nosql", "document", "database"] },
  { name: "SiRedis", icon: SiRedis, category: "Databases", tags: ["cache", "memory", "database"] },
  { name: "SiElasticsearch", icon: SiElasticsearch, category: "Databases", tags: ["search", "analytics", "elk"] },
  { name: "SiStripe", icon: SiStripe, category: "Payments", tags: ["payment", "checkout", "money"] },
  { name: "SiPaypal", icon: SiPaypal, category: "Payments", tags: ["payment", "money", "transfer"] },
  { name: "SiVisa", icon: SiVisa, category: "Payments", tags: ["card", "credit", "payment"] },
  { name: "SiMastercard", icon: SiMastercard, category: "Payments", tags: ["card", "credit", "payment"] },
  { name: "SiSlack", icon: SiSlack, category: "Communication", tags: ["chat", "team", "messaging"] },
  { name: "SiDiscord", icon: SiDiscord, category: "Communication", tags: ["chat", "gaming", "community"] },
  { name: "SiTelegram", icon: SiTelegram, category: "Communication", tags: ["messaging", "chat", "secure"] },
  { name: "SiWhatsapp", icon: SiWhatsapp, category: "Communication", tags: ["messaging", "chat", "mobile"] },
  { name: "SiX", icon: SiX, category: "Social", tags: ["twitter", "tweets", "social"] },
  { name: "SiLinkedin", icon: SiLinkedin, category: "Social", tags: ["professional", "network", "jobs"] },
  { name: "SiFacebook", icon: SiFacebook, category: "Social", tags: ["meta", "social", "network"] },
  { name: "SiInstagram", icon: SiInstagram, category: "Social", tags: ["photos", "social", "meta"] },
  { name: "SiYoutube", icon: SiYoutube, category: "Social", tags: ["video", "google", "streaming"] },
  { name: "SiTwitch", icon: SiTwitch, category: "Social", tags: ["streaming", "gaming", "live"] },
  { name: "SiSpotify", icon: SiSpotify, category: "Media", tags: ["music", "streaming", "audio"] },
  { name: "SiNetflix", icon: SiNetflix, category: "Media", tags: ["streaming", "video", "movies"] },
  { name: "SiAmazon", icon: SiAmazon, category: "Companies", tags: ["aws", "shopping", "cloud"] },
  { name: "SiDropbox", icon: SiDropbox, category: "Cloud", tags: ["storage", "files", "sync"] },
  { name: "SiNotion", icon: SiNotion, category: "Productivity", tags: ["notes", "docs", "workspace"] },
  { name: "SiFigma", icon: SiFigma, category: "Design", tags: ["ui", "design", "prototype"] },
  { name: "SiVercel", icon: SiVercel, category: "Cloud", tags: ["deploy", "hosting", "next"] },
  { name: "SiNetlify", icon: SiNetlify, category: "Cloud", tags: ["deploy", "hosting", "jamstack"] },
  { name: "SiHeroku", icon: SiHeroku, category: "Cloud", tags: ["deploy", "paas", "hosting"] },
  { name: "SiDigitalocean", icon: SiDigitalocean, category: "Cloud", tags: ["vps", "cloud", "hosting"] },
  { name: "SiCloudflare", icon: SiCloudflare, category: "Cloud", tags: ["cdn", "dns", "security"] },
  { name: "SiNginx", icon: SiNginx, category: "Development", tags: ["server", "proxy", "web"] },
  { name: "SiApache", icon: SiApache, category: "Development", tags: ["server", "web", "httpd"] },
  { name: "SiJenkins", icon: SiJenkins, category: "Development", tags: ["ci", "cd", "automation"] },
  { name: "SiGitlab", icon: SiGitlab, category: "Development", tags: ["git", "ci", "devops"] },
  { name: "SiBitbucket", icon: SiBitbucket, category: "Development", tags: ["git", "atlassian", "code"] },
];

const allCategories = Array.from(
  new Set([...lucideIcons, ...brandIcons].map(i => i.category))
).sort();

export default function IconsReference() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [copiedIcon, setCopiedIcon] = useState<string | null>(null);

  const filteredLucideIcons = useMemo(() => {
    return lucideIcons.filter(icon => {
      const matchesSearch = searchTerm === "" || 
        icon.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        icon.tags.some(tag => tag.toLowerCase().includes(searchTerm.toLowerCase()));
      const matchesCategory = selectedCategory === null || icon.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchTerm, selectedCategory]);

  const filteredBrandIcons = useMemo(() => {
    return brandIcons.filter(icon => {
      const matchesSearch = searchTerm === "" || 
        icon.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        icon.tags.some(tag => tag.toLowerCase().includes(searchTerm.toLowerCase()));
      const matchesCategory = selectedCategory === null || icon.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchTerm, selectedCategory]);

  const copyIconName = (name: string) => {
    navigator.clipboard.writeText(name);
    setCopiedIcon(name);
    setTimeout(() => setCopiedIcon(null), 2000);
  };

  const lucideCategories = Array.from(new Set(lucideIcons.map(i => i.category))).sort();
  const brandCategories = Array.from(new Set(brandIcons.map(i => i.category))).sort();

  return (
    <ScrollArea className="h-full">
      <div className="p-6 space-y-6 max-w-6xl mx-auto">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold" data-testid="text-page-title">Icons Reference</h1>
          <p className="text-muted-foreground">
            Available icons from lucide-react and react-icons. Click to copy the import name.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input 
              className="pl-8" 
              placeholder="Search icons by name or tag..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              data-testid="input-search-icons"
            />
          </div>
          <div className="flex gap-2 flex-wrap">
            <Badge 
              variant={selectedCategory === null ? "default" : "outline"}
              className="cursor-pointer"
              onClick={() => setSelectedCategory(null)}
              data-testid="filter-all"
            >
              All ({lucideIcons.length + brandIcons.length})
            </Badge>
          </div>
        </div>

        <Tabs defaultValue="lucide" className="w-full">
          <TabsList>
            <TabsTrigger value="lucide" data-testid="tab-lucide">
              Lucide ({filteredLucideIcons.length})
            </TabsTrigger>
            <TabsTrigger value="brands" data-testid="tab-brands">
              Brands ({filteredBrandIcons.length})
            </TabsTrigger>
          </TabsList>

          <TabsContent value="lucide" className="space-y-4">
            <div className="flex gap-2 flex-wrap">
              {lucideCategories.map(cat => (
                <Badge 
                  key={cat}
                  variant={selectedCategory === cat ? "default" : "outline"}
                  className="cursor-pointer text-xs"
                  onClick={() => setSelectedCategory(selectedCategory === cat ? null : cat)}
                  data-testid={`filter-${cat.toLowerCase()}`}
                >
                  {cat}
                </Badge>
              ))}
            </div>

            <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 gap-2">
              {filteredLucideIcons.map((item) => (
                <Tooltip key={item.name}>
                  <TooltipTrigger asChild>
                    <Card 
                      className={`p-2 cursor-pointer hover-elevate ${copiedIcon === item.name ? 'ring-2 ring-primary' : ''}`}
                      onClick={() => copyIconName(item.name)}
                      data-testid={`icon-${item.name.toLowerCase()}`}
                    >
                      <div className="flex flex-col items-center gap-1">
                        <item.icon className="h-5 w-5" />
                        <span className="text-[9px] text-muted-foreground truncate w-full text-center">
                          {item.name}
                        </span>
                      </div>
                    </Card>
                  </TooltipTrigger>
                  <TooltipContent>
                    <div className="text-xs">
                      <p className="font-medium">{item.name}</p>
                      <p className="text-muted-foreground">{item.category}</p>
                      <p className="text-muted-foreground">{item.tags.join(", ")}</p>
                      <p className="text-primary mt-1">Click to copy</p>
                    </div>
                  </TooltipContent>
                </Tooltip>
              ))}
            </div>

            {filteredLucideIcons.length === 0 && (
              <div className="text-center py-8 text-muted-foreground">
                No icons found matching "{searchTerm}"
              </div>
            )}
          </TabsContent>

          <TabsContent value="brands" className="space-y-4">
            <div className="flex gap-2 flex-wrap">
              {brandCategories.map(cat => (
                <Badge 
                  key={cat}
                  variant={selectedCategory === cat ? "default" : "outline"}
                  className="cursor-pointer text-xs"
                  onClick={() => setSelectedCategory(selectedCategory === cat ? null : cat)}
                  data-testid={`filter-brand-${cat.toLowerCase()}`}
                >
                  {cat}
                </Badge>
              ))}
            </div>

            <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 gap-2">
              {filteredBrandIcons.map((item) => (
                <Tooltip key={item.name}>
                  <TooltipTrigger asChild>
                    <Card 
                      className={`p-2 cursor-pointer hover-elevate ${copiedIcon === item.name ? 'ring-2 ring-primary' : ''}`}
                      onClick={() => copyIconName(item.name)}
                      data-testid={`icon-${item.name.toLowerCase()}`}
                    >
                      <div className="flex flex-col items-center gap-1">
                        <item.icon className="h-5 w-5" />
                        <span className="text-[9px] text-muted-foreground truncate w-full text-center">
                          {item.name.replace('Si', '')}
                        </span>
                      </div>
                    </Card>
                  </TooltipTrigger>
                  <TooltipContent>
                    <div className="text-xs">
                      <p className="font-medium">{item.name}</p>
                      <p className="text-muted-foreground">from react-icons/si</p>
                      <p className="text-muted-foreground">{item.tags.join(", ")}</p>
                      <p className="text-primary mt-1">Click to copy</p>
                    </div>
                  </TooltipContent>
                </Tooltip>
              ))}
            </div>

            {filteredBrandIcons.length === 0 && (
              <div className="text-center py-8 text-muted-foreground">
                No brand icons found matching "{searchTerm}"
              </div>
            )}
          </TabsContent>
        </Tabs>

        <Separator />

        <Card>
          <CardHeader>
            <CardTitle>Usage</CardTitle>
            <CardDescription>How to import and use icons</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-medium text-sm mb-2">Lucide Icons (lucide-react)</h3>
              <pre className="bg-muted p-3 rounded text-xs overflow-x-auto">
{`import { Search, Plus, Settings } from "lucide-react";

<Search className="h-4 w-4" />
<Plus className="h-5 w-5 text-primary" />`}
              </pre>
            </div>
            <div>
              <h3 className="font-medium text-sm mb-2">Brand Icons (react-icons)</h3>
              <pre className="bg-muted p-3 rounded text-xs overflow-x-auto">
{`import { SiBitcoin, SiGithub } from "react-icons/si";

<SiBitcoin className="h-4 w-4" />
<SiGithub className="h-5 w-5 text-muted-foreground" />`}
              </pre>
            </div>
          </CardContent>
        </Card>

        <div className="h-8" />
      </div>
    </ScrollArea>
  );
}
