// @vitest-environment jsdom
//
// Regression guard for the garbled-text vector in the Fund Trail PDF export
// (`buildFundTrailPdf` in fund-trail-export.ts).
//
// jsPDF's Standard-14 Helvetica has no embedded Unicode font, so any text run
// outside the WinAnsi (Windows-1252) range is emitted as a UTF-16BE byte stream
// that renders as garbled glyphs. The fix routes record-derived strings (center
// label, group labels, intermediary "via:" chains, and the detailed detail-row
// addresses/txids) through `sanitizePdfText`. If a future edit drops one of those
// wrappers, a non-Latin address or label would silently reintroduce a UTF-16BE
// run. This feeds non-WinAnsi text into every record-derived surface and asserts
// the generated PDF contains NO UTF-16BE runs.
//
// `buildFundTrailPdf` returns a Blob directly (doc.output("blob")), so we just
// inspect the real generated bytes — no doc.save/fs trick needed.

import { describe, it, expect } from "vitest";

import { extractPdfText, pdfHasUtf16beRuns } from "@/test/pdfAssertions";
import {
  buildFundTrailPdf,
  type FundTrailSnapshot,
  type ExportFlowNode,
} from "./fund-trail-export";

// Non-WinAnsi strings: CJK names and addresses all live above U+00FF, so before
// sanitization they would each force a UTF-16BE run.
const NON_LATIN_CENTER = "錢包_測試";
const NON_LATIN_GROUP = "魏健_group";
const NON_LATIN_ADDR = "bc1q魏健address0000000000000000000000000000aa";
const NON_LATIN_TXID = "魏健" + "f".repeat(60);
const NON_LATIN_VIA = "bc1q段_中間00000000000000000000000000000000aa";

function node(overrides: Partial<ExportFlowNode> = {}): ExportFlowNode {
  return {
    groupLabel: NON_LATIN_GROUP,
    totalSats: 100_000_000,
    isUnknown: false,
    details: [
      {
        address: NON_LATIN_ADDR,
        txid: NON_LATIN_TXID,
        amount: 100_000_000,
        blockTime: 1_700_000_000,
      },
    ],
    children: [],
    ...overrides,
  };
}

function snapshot(): FundTrailSnapshot {
  return {
    centerLabel: NON_LATIN_CENTER,
    dimension: "walletName",
    generatedAt: new Date("2025-06-15T08:00:00Z").toISOString(),
    sources: [
      node({
        // A multi-hop node carries a chain of intermediary addresses rendered
        // inline as a "via:" line — another record-derived surface.
        hopDepth: 2,
        pathAddresses: [NON_LATIN_VIA],
      }),
    ],
    destinations: [node()],
    cap: { capped: false, shownTxCount: 0, totalTxCount: 0, cappedHopCount: 0 },
  };
}

describe("Fund Trail PDF — WinAnsi safety", () => {
  it("emits no UTF-16BE runs even with non-Latin labels, addresses and txids", async () => {
    // detailed=true also renders the per-group detail tables (addresses/txids).
    const blob = await buildFundTrailPdf(snapshot(), { detailed: true });

    // The smoking gun: any UTF-16BE run means a record-derived string skipped
    // sanitizePdfText and will render as garbled glyphs.
    expect(await pdfHasUtf16beRuns(blob)).toBe(false);

    const text = await extractPdfText(blob);
    // ASCII scaffolding proves the document rendered (not dropped) and the
    // non-Latin glyphs were substituted with "?".
    expect(text).toContain("Fund Trail");
    expect(text).toContain("Wallet:");
    expect(text).toContain("?");
  });

  it("would catch a bypass: raw non-Latin text DOES produce UTF-16BE runs", async () => {
    // Control proving the guard above is meaningful: render the same non-Latin
    // text WITHOUT sanitizePdfText via a bare jsPDF doc. This is exactly what a
    // regression (dropping the wrapper) would emit — and it must trip the
    // detector, otherwise the assertions above could pass vacuously.
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    doc.text(`Address: ${NON_LATIN_ADDR}`, 14, 20);
    const rawBlob = doc.output("blob");
    expect(await pdfHasUtf16beRuns(rawBlob)).toBe(true);
  });
});
